---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  sqlite3
  database: sample_development.db
 
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.db
  #   repo2:
  #     ...
 
test:
  <<:       *defaults
  database: sample_test.db
 
  # repositories:
  #   repo1:
  #     database: sample_1_test.db
 
production:
  :adapter: mysql
  :database: merbist
  :username: root
  :password: 
  :host: localhost
  :socket: /var/run/mysqld/mysqld.sock
  :encoding: utf8

 
  # repositories:
  #   repo1:
  #     database: sample_production.db
 
rake:
  <<: *defaults
